### PR TITLE
Add build script for MacOS and Linux

### PR DESCRIPTION
**Pull request by luizcavalcanti**
### An early tentative build for Recognizers-Text as a library on linux and macOS.

**Status**
* It builds :)
* It can be imported as a .net assembly by the demo applications, compile with them and executed perfectly as far as I could try.

**Issues**
* Had to manually create the target platform on buildfiles for that purpose (sorry, I'm clueless with MSBuild)
* Could not make vstest run on macOS.
* Was only tested on macOS 10.13.2 and Arch Linux with kernel 4.14.4 (both with dotnet-sdk 2.1 and msbuild 15.4), so I don't really know how solid this is different environments.

Signed-off-by: Luiz Carlos Cavalcanti <cavalcanti.luiz@gmail.com>

### CODE REVIEW

**Comment by tellarin** [comment]
Thanks @luizcavalcanti!

**Comment by luizcavalcanti** [comment]
Still not successfuly compiling the .Net packages on MacOS:

Tests cannot be run because we lack Microsoft Data Access Components(MDAC). Is it even possible to get it installed on MacOS?

```
The unit test adapter failed to connect to the data source or to read the data. 
For more information on troubleshooting this error, see "Troubleshooting 
Data-Driven Unit Tests" (http://go.microsoft.com/fwlink/?LinkId=62412) in 
the MSDN Library. Error details: The .Net Framework Data Providers require 
Microsoft Data Access Components(MDAC).  Please install Microsoft Data 
Access Components(MDAC) version 2.6 or later.

```

**Comment by tellarin** [comment]
@luizcavalcanti Any idea what it runs on Linux? We may start looking back into this again soon.

**Comment by luizcavalcanti** [comment]
Hmmm, no. 

I'll update my whole (very outdated) toolchain and try it again. For linux, specifically, I'll try in a VM or even on a docker container, and see how it goes.

Hopefully this weekend I'll have the time to try it all.

**Comment by hansmbakker** [comment]
Migrating the tests to .Net Core as-is is not possible until https://github.com/Microsoft/testfx/issues/233 (`DataSourceAttribute` / `DataRow` for .Net Core) is fixed.

**Comment by luizcavalcanti** [comment]
Thanks to a lot of recent changes, specially PR #1050, the build && test script if finally working completely on macOS. I'm removing the WIP status, if it's OK, @tellarin

**Pull request merged**
