### PR TITLE
[EN DateTimeV2] Merge separate datetime phrase results (#1492)

### PR DESCRIPTION
**Pull request by LionbridgeCSII**
Partial fix to issue #1492.

Added relevant test cases to DateTimeModel.

Note that the original example pointed out in #1942, "between 7 and 9 last night", does not behave as described in the issue because "between 7 and 9" is not extracted as TimePeriod (instead '9 last night' is extracted as DateTime). 
Consequently, it is not supported by the current fix and additional work is required to cover it.

### CODE REVIEW

**Comment by tellarin** [comment]
@LionbridgeCSII, could you solve the conflicts here? We'll prioritize the review to merge.

**Comment by LionbridgeCSII** [comment]
> @LionbridgeCSII, could you solve the conflicts here? We'll prioritize the review to merge.

@tellarin, conflicts solved

**Review by tellarin — APPROVED** [review]
Please resolve the conflicts and create a new issue to represent the part of the previous issue not solved.
Thanks.

**Comment by LionbridgeCSII** [comment]
> Please resolve the conflicts and create a new issue to represent the part of the previous issue not solved.
> Thanks.

Conflict solved.

**Pull request merged**
