### PR TITLE
[JavaScript] Support build on Ubuntu Linux #1773

### LINKED ISSUE #1771: [JA DateTime] How to suggest spec bug fix?
**Is your feature request related to a problem? Please describe.**
I'm glad that this project has excellent translated Japanese DateTime Spec even though Patterns have some Chinese-only phrases and grammar which is clearly not Japanese ones...

However, I found some bugs on spec. Let's take a look at an [example on DatePeriodParser.json](https://github.com/microsoft/Recognizers-Text/blob/57800ad42419bd8c3898d2b5bc1d6a50f1ee4160/Specs/DateTime/Japanese/DatePeriodParser.json#L894
):

```json
  {
    "Input": "10月2日から10月22日まで不在にします。",
    "Context": {
      "ReferenceDateTime": "2016-11-07T00:00:00"
    },
    "NotSupported": "dotnet",
    "NotSupportedByDesign": "javascript,python,java",
    "Results": [
      {
        "Text": "10月2日から10月22日まで",
        "Type": "daterange",
        "Value": {
          "Timex": "(XXXX-10-02,XXXX-10-22,P20D)",
          "FutureResolution": {
            "startDate": "2017-10-02",
            "endDate": "2017-10-22"
          },
          "PastResolution": {
            "startDate": "2016-10-02",
            "endDate": "2016-10-22"
          }
        },
        "Start": 12,
        "Length": 25
      }
    ]
  },
```

Extracted string doesn't begin at index 12, it's from the beginning. And length is 15, not 22. This kind of bugs are easily fixable, I believe. A bit tough example is something like [this](https://github.com/microsoft/Recognizers-Text/blob/57800ad42419bd8c3898d2b5bc1d6a50f1ee4160/Specs/DateTime/Japanese/DateParser.json#L2612):

```
  {
    "Input": "私は1日の日曜日に戻ります",
    "Context": {
      "ReferenceDateTime": "2017-09-27T00:00:00"
    },
    "NotSupportedByDesign": "dotNet, javascript, python, java",
    "Results": [
      {
        "Text": "1日の日曜日",
        "Type": "date",
        "Value": {
          "Timex": "2017-09-03",
          "FutureResolution": {
            "date": "2017-09-03"
          },
          "PastResolution": {
            "date": "2017-09-03"
          }
        },
        "Start": 2,
        "Length": 6
      }
    ]
  },
```

Here we can see "1日の日曜日" but let's see [another example on same spec file](https://github.com/microsoft/Recognizers-Text/blob/57800ad42419bd8c3898d2b5bc1d6a50f1ee4160/Specs/DateTime/Japanese/DateParser.json#L203):

```json
  {
    "Input": "7月の第1金曜日に戻ります。",
    "Context": {
      "ReferenceDateTime": "2016-11-07T00:00:00"
    },
    "NotSupported": "dotnet",
    "NotSupportedByDesign": "javascript,python,java",
    "Results": [
      {
        "Text": "7月の第1金曜日",
        "Type": "date",
        "Value": {
          "Timex": "XXXX-07-WXX-5-#1",
          "FutureResolution": {
            "date": "2017-07-07"
          },
          "PastResolution": {
            "date": "2016-07-01"
          }
        },
        "Start": 13,
        "Length": 24
      }
    ]
  }
```

Way of describing 'nth weekday' in Japanese form is later one, not previous one. This kind of grammatical error on Spec needs to be fixed, I believe.

Toughest ones might be [something like this](https://github.com/microsoft/Recognizers-Text/blob/57800ad42419bd8c3898d2b5bc1d6a50f1ee4160/Specs/DateTime/Japanese/DateTimeParser.json#L621):

```json
  {
    "Input": "私は2016年04月21日の午後8:00に戻ります",
    "Context": {
      "ReferenceDateTime": "2016-11-07T00:00:00"
    },
    "NotSupportedByDesign": "dotnet,javascript,python,java",
    "Results": [
      {
        "Text": "04/21/2016, 8:00pm",
        "Type": "datetime",
        "Value": {
          "Timex": "2016-04-21T20:00",
          "FutureResolution": {
            "dateTime": "2016-04-21 20:00:00"
          },
          "PastResolution": {
            "dateTime": "2016-04-21 20:00:00"
          }
        },
        "Start": 2,
        "Length": 18
      }
    ]
  },
```

Extracted string should be `2016年04月21日の午後8:00`. Input text is well translated. But, unfortunately, result text part isn't translated.

**Describe the solution you'd like**
I personally made some patches to fix these bugs, but since I'm a Python user and there isn't Python Japanese DateTime model available yet, I'm not sure the way to validate my patch.

Even worse, I only have a Ubuntu machine, so it's not easy for me to figure out how to run some tests on other Programming languages, such as DotNet. (I found that there is some problem running DotNet package of this project on Ubuntu, some kind of version problem.)

So I need a guide how to create a pull request with ensured quality check.

**Describe alternatives you've considered**
Or someone other than me could fix those bugs in Spec and make proper full request... I made a dirty script [fix_spec_error.zip](https://github.com/microsoft/Recognizers-Text/files/3467000/fix_spec_error.zip) to automatically fix some trivial Spec error. Of course this lacks with some other spec bug fix.

**Additional context**
Of course, it would be very appreciated if someone would guide me how to make pull request by my own. Of course I've already read [Contributing guide](https://blog.botframework.com/2018/02/12/contributing-luis-microsoft-recognizers-text-part-3/) but it only tells about JavaScript and DotNet, not about other Programming language, and I'm keep failing to run DotNet ones on my local machine...

Thanks for reading.

### LINKED ISSUE #1773: [JavaScript] Can't build on Ubuntu Linux due to the file name upper/lowercase mismatches
**Describe the bug**
Unlike Windows NTFS file system, on Linux, we need to ensure that file name must matches with its upper/lowercase status. If the filename is 'timexRegex.js', then we must not use 'timexregex.js' to open that file, since there is a upper/lowercase mismatch. 

I tried to build JavaScript package on my Ubuntu 18.04.2 LTS and failed. I found several module name upper/lowercase mismatches on the source code.

**To Reproduce**
0. Prepare Ubuntu Linux 18.04.2 installed.
1. Go to 'JavaScript' folder, by typing `cd JavaScript`, on the repository.
2. Execute `bash ./build.sh`
3. ....

**Expected behavior**
No error at all.

**Sample input/output**
```
npm run build

> recognizers@1.1.4 build /data/personal/Recognizers-Text/JavaScript
> lerna clean --yes && lerna bootstrap --hoist

lerna info version 2.11.0
lerna info clean removing /data/personal/Recognizers-Text/JavaScript/packages/recognizers-choice/node_modules
lerna info clean removing /data/personal/Recognizers-Text/JavaScript/packages/recognizers-date-time/node_modules
lerna info clean removing /data/personal/Recognizers-Text/JavaScript/packages/recognizers-number-with-unit/node_modules
lerna info clean removing /data/personal/Recognizers-Text/JavaScript/packages/recognizers-number/node_modules
lerna info clean removing /data/personal/Recognizers-Text/JavaScript/packages/recognizers-sequence/node_modules
lerna info clean removing /data/personal/Recognizers-Text/JavaScript/packages/recognizers-text-suite/node_modules
lerna info clean removing /data/personal/Recognizers-Text/JavaScript/packages/recognizers-text/node_modules
lerna info clean removing /data/personal/Recognizers-Text/JavaScript/packages/datatypes-date-time/node_modules
lerna success clean finished
lerna info version 2.11.0
lerna info Bootstrapping 8 packages
lerna info lifecycle preinstall
lerna info Installing external dependencies
lerna info hoist Installing hoisted dependencies into root
lerna info hoist Pruning hoisted dependencies
lerna info hoist Finished pruning hoisted dependencies
lerna info hoist Finished installing in root
lerna info Symlinking packages and binaries
lerna WARN EREPLACE_EXIST @microsoft/recognizers-text is already installed for @microsoft/recognizers-text-choice. Replacing with symlink...
lerna WARN EREPLACE_EXIST @microsoft/recognizers-text is already installed for @microsoft/recognizers-text-date-time. Replacing with symlink...
lerna WARN EREPLACE_EXIST @microsoft/recognizers-text-number is already installed for @microsoft/recognizers-text-date-time. Replacing with symlink...
lerna WARN EREPLACE_EXIST @microsoft/recognizers-text-number-with-unit is already installed for @microsoft/recognizers-text-date-time. Replacing with symlink...
lerna WARN EREPLACE_EXIST @microsoft/recognizers-text is already installed for @microsoft/recognizers-text-number-with-unit. Replacing with symlink...
lerna WARN EREPLACE_EXIST @microsoft/recognizers-text-number is already installed for @microsoft/recognizers-text-number-with-unit. Replacing with symlink...
lerna WARN EREPLACE_EXIST @microsoft/recognizers-text is already installed for @microsoft/recognizers-text-number. Replacing with symlink...
lerna WARN EREPLACE_EXIST @microsoft/recognizers-text is already installed for @microsoft/recognizers-text-sequence. Replacing with symlink...
lerna WARN EREPLACE_EXIST @microsoft/recognizers-text is already installed for @microsoft/recognizers-text-suite. Replacing with symlink...
lerna WARN EREPLACE_EXIST @microsoft/recognizers-text-number is already installed for @microsoft/recognizers-text-suite. Replacing with symlink...
lerna WARN EREPLACE_EXIST @microsoft/recognizers-text-number-with-unit is already installed for @microsoft/recognizers-text-suite. Replacing with symlink...
lerna WARN EREPLACE_EXIST @microsoft/recognizers-text-date-time is already installed for @microsoft/recognizers-text-suite. Replacing with symlink...
lerna WARN EREPLACE_EXIST @microsoft/recognizers-text-sequence is already installed for @microsoft/recognizers-text-suite. Replacing with symlink...
lerna WARN EREPLACE_EXIST @microsoft/recognizers-text-choice is already installed for @microsoft/recognizers-text-suite. Replacing with symlink...
lerna info lifecycle postinstall
lerna info lifecycle prepublish
lerna info lifecycle prepare
lerna ERR! execute Error occured with '@microsoft/recognizers-text-data-types-timex-expression' while running 'npm run prepare'
lerna ERR! npm run prepare [@microsoft/recognizers-text-data-types-timex-expression] Output from stdout:

> @microsoft/recognizers-text-data-types-timex-expression@1.1.4 prepare /data/personal/Recognizers-Text/JavaScript/packages/datatypes-date-time
> npm run clean-build && rollup -c


> @microsoft/recognizers-text-data-types-timex-expression@1.1.4 clean-build /data/personal/Recognizers-Text/JavaScript/packages/datatypes-date-time
> rimraf dist


lerna ERR! npm run prepare [@microsoft/recognizers-text-data-types-timex-expression] Output from stderr:

index.js → dist/recognizers-text-data-types-timex-expression.es5.js, dist/recognizers-text-data-types-timex-expression.umd.js, dist/recognizers-text-data-types-timex-expression.browser.js...
[!] Error: Could not resolve './timexregex.js' from src/timexParsing.js
Error: Could not resolve './timexregex.js' from src/timexParsing.js
    at error (/data/personal/Recognizers-Text/JavaScript/node_modules/rollup/dist/rollup.js:185:14)
    at then.resolvedId (/data/personal/Recognizers-Text/JavaScript/node_modules/rollup/dist/rollup.js:10124:8)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @microsoft/recognizers-text-data-types-timex-expression@1.1.4 prepare: `npm run clean-build && rollup -c`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @microsoft/recognizers-text-data-types-timex-expression@1.1.4 prepare script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/khbyun/.npm/_logs/2019-08-05T13_08_17_419Z-debug.log

lerna ERR! execute Error occured with '@microsoft/recognizers-text-data-types-timex-expression' while running 'npm run prepare'
lerna WARN complete Waiting for 1 child process to exit. CTRL-C to exit immediately.
{ Error: Command failed: npm run prepareplete Waiting for 1 child process to exit. CTRL-C to exit immediately.

index.js → dist/recognizers-text-data-types-timex-expression.es5.js, dist/recognizers-text-data-types-timex-expression.umd.js, dist/recognizers-text-data-types-timex-expression.browser.js...
[!] Error: Could not resolve './timexregex.js' from src/timexParsing.js
Error: Could not resolve './timexregex.js' from src/timexParsing.js
    at error (/data/personal/Recognizers-Text/JavaScript/node_modules/rollup/dist/rollup.js:185:14)
    at then.resolvedId (/data/personal/Recognizers-Text/JavaScript/node_modules/rollup/dist/rollup.js:10124:8)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @microsoft/recognizers-text-data-types-timex-expression@1.1.4 prepare: `npm run clean-build && rollup -c`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @microsoft/recognizers-text-data-types-timex-expression@1.1.4 prepare script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/khbyun/.npm/_logs/2019-08-05T13_08_17_419Z-debug.log

> @microsoft/recognizers-text-data-types-timex-expression@1.1.4 prepare /data/personal/Recognizers-Text/JavaScript/packages/datatypes-date-time
> npm run clean-build && rollup -c


> @microsoft/recognizers-text-data-types-timex-expression@1.1.4 clean-build /data/personal/Recognizers-Text/JavaScript/packages/datatypes-date-time
> rimraf dist


    at Promise.all.then.arr (/data/personal/Recognizers-Text/JavaScript/node_modules/lerna/node_modules/execa/index.js:236:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  code: 1,
  killed: false,
  stdout:
   '\n> @microsoft/recognizers-text-data-types-timex-expression@1.1.4 prepare /data/personal/Recognizers-Text/JavaScript/packages/datatypes-date-time\n> npm run clean-build && rollup -c\n\n\n> @microsoft/recognizers-text-data-types-timex-expression@1.1.4 clean-build /data/personal/Recognizers-Text/JavaScript/packages/datatypes-date-time\n> rimraf dist\n\n',
  stderr:
   '\nindex.js → dist/recognizers-text-data-types-timex-expression.es5.js, dist/recognizers-text-data-types-timex-expression.umd.js, dist/recognizers-text-data-types-timex-expression.browser.js...\n[!] Error: Could not resolve \'./timexregex.js\' from src/timexParsing.js\nError: Could not resolve \'./timexregex.js\' from src/timexParsing.js\n    at error (/data/personal/Recognizers-Text/JavaScript/node_modules/rollup/dist/rollup.js:185:14)\n    at then.resolvedId (/data/personal/Recognizers-Text/JavaScript/node_modules/rollup/dist/rollup.js:10124:8)\n\nnpm ERR! code ELIFECYCLE\nnpm ERR! errno 1\nnpm ERR! @microsoft/recognizers-text-data-types-timex-expression@1.1.4 prepare: `npm run clean-build && rollup -c`\nnpm ERR! Exit status 1\nnpm ERR! \nnpm ERR! Failed at the @microsoft/recognizers-text-data-types-timex-expression@1.1.4 prepare script.\nnpm ERR! This is probably not a problem with npm. There is likely additional logging output above.\nnpm WARN Local package.json exists, but node_modules missing, did you mean to install?\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /home/khbyun/.npm/_logs/2019-08-05T13_08_17_419Z-debug.log\n',
  failed: true,
  signal: null,
  cmd: 'npm run prepare',
  timedOut: false,
  pkg:
   Package {
     _package:
      { name: '@microsoft/recognizers-text-data-types-timex-expression',
        version: '1.1.4',
        description: 'Support for TIMEX representation of data time',
        author: 'Microsoft',
        license: 'MIT',
        keywords: [Array],
        main: 'dist/recognizers-text-data-types-timex-expression.umd.js',
        module: 'dist/recognizers-text-data-types-timex-expression.es5.js',
        browser:
         'dist/recognizers-text-data-types-timex-expression.browser.js',
        repository: [Object],
        bugs: [Object],
        engines: [Object],
        scripts: [Object],
        devDependencies: [Object] },
     _location:
      '/data/personal/Recognizers-Text/JavaScript/packages/datatypes-date-time' },
  exitCode: 1 }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! recognizers@1.1.4 build: `lerna clean --yes && lerna bootstrap --hoist`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the recognizers@1.1.4 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/khbyun/.npm/_logs/2019-08-05T13_08_20_500Z-debug.log
```

**Platform (please complete the following information):**
 - Platform: [JavaScript]
 - Environment: [Node v10.16.0]
 - Version of package [master branch]

**Additional context**
Would it be OK for me to try to create a pull request regarding this? Unfortunately I won't find easy way to check if it will work on Windows though.

### PR DESCRIPTION
**Pull request by combacsa**
* Fixes #1773

(I'm not sure why chineseNumeric.ts is modified on this pull request though.)

### CODE REVIEW

**Comment by FeifanLiu98** [comment]
Sorry for my mistake. I think the reason why chineseNumeric.ts is modified is the inconsistency of chineseNumeric.ts and Chinese-numbers.yaml. I will fix it.

**Comment by combacsa** [comment]
> Sorry for my mistake. I think the reason why chineseNumeric.ts is modified is the inconsistency of chineseNumeric.ts and Chinese-numbers.yaml. I will fix it.

I see. Could you please let me know what actions should do? Since it's my kinda very first time on sending a pull request, I'm not so sure about the way editing commits... Could you verify my guess below? 

- You'll create a pull request regarding Chinese-numbers.yaml (Maybe you'll need to check other programming languages as well - such as Java)
- I'll revert the change on `JavaScript/packages/recognizers-number/src/resources/chineseNumeric.ts` on my CL in my local repository, and `git commit --amend`, and `git push --force` to my local github repository
- Everyone happy with parallel executions of different issues

**Comment by tellarin** [comment]
@combacsa I've re-generated some auto-generated files that were out-of-date and pushed them here too. Please confirm the build on Linux works.
I'll merge these after the CI build (Windows) passes.

**Comment by combacsa** [comment]
@tellarin I now confirmed that it works on Linux.

```
$ ./build.sh
// Building Javacript platform
// Installing dependencies
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.0.7 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.0.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 1338 packages from 533 contributors and audited 8582 packages in 11.859s
found 54 high severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
// Building - npm run build

> recognizers@1.1.4 build /data/personal/Recognizers-Text/JavaScript
> lerna clean --yes && lerna bootstrap --hoist

lerna info version 2.11.0
lerna info clean removing /data/personal/Recognizers-Text/JavaScript/packages/recognizers-choice/node_modules
lerna info clean removing /data/personal/Recognizers-Text/JavaScript/packages/recognizers-date-time/node_modules
lerna info clean removing /data/personal/Recognizers-Text/JavaScript/packages/recognizers-number-with-unit/node_modules
lerna info clean removing /data/personal/Recognizers-Text/JavaScript/packages/recognizers-number/node_modules
lerna info clean removing /data/personal/Recognizers-Text/JavaScript/packages/recognizers-sequence/node_modules
lerna info clean removing /data/personal/Recognizers-Text/JavaScript/packages/recognizers-text-suite/node_modules
lerna info clean removing /data/personal/Recognizers-Text/JavaScript/packages/recognizers-text/node_modules
lerna info clean removing /data/personal/Recognizers-Text/JavaScript/packages/datatypes-date-time/node_modules
lerna success clean finished
lerna info version 2.11.0
lerna info Bootstrapping 8 packages
lerna info lifecycle preinstall
lerna info Installing external dependencies
lerna info hoist Installing hoisted dependencies into root
lerna info hoist Pruning hoisted dependencies
lerna info hoist Finished pruning hoisted dependencies
lerna info hoist Finished installing in root
lerna info Symlinking packages and binaries
lerna WARN EREPLACE_EXIST @microsoft/recognizers-text is already installed for @microsoft/recognizers-text-choice. Replacing with symlink...
lerna WARN EREPLACE_EXIST @microsoft/recognizers-text is already installed for @microsoft/recognizers-text-date-time. Replacing with symlink...
lerna WARN EREPLACE_EXIST @microsoft/recognizers-text-number is already installed for @microsoft/recognizers-text-date-time. Replacing with symlink...
lerna WARN EREPLACE_EXIST @microsoft/recognizers-text-number-with-unit is already installed for @microsoft/recognizers-text-date-time. Replacing with symlink...
lerna WARN EREPLACE_EXIST @microsoft/recognizers-text is already installed for @microsoft/recognizers-text-number-with-unit. Replacing with symlink...
lerna WARN EREPLACE_EXIST @microsoft/recognizers-text-number is already installed for @microsoft/recognizers-text-number-with-unit. Replacing with symlink...
lerna WARN EREPLACE_EXIST @microsoft/recognizers-text is already installed for @microsoft/recognizers-text-number. Replacing with symlink...
lerna WARN EREPLACE_EXIST @microsoft/recognizers-text is already installed for @microsoft/recognizers-text-sequence. Replacing with symlink...
lerna WARN EREPLACE_EXIST @microsoft/recognizers-text is already installed for @microsoft/recognizers-text-suite. Replacing with symlink...
lerna WARN EREPLACE_EXIST @microsoft/recognizers-text-number is already installed for @microsoft/recognizers-text-suite. Replacing with symlink...
lerna WARN EREPLACE_EXIST @microsoft/recognizers-text-number-with-unit is already installed for @microsoft/recognizers-text-suite. Replacing with symlink...
lerna WARN EREPLACE_EXIST @microsoft/recognizers-text-date-time is already installed for @microsoft/recognizers-text-suite. Replacing with symlink...
lerna WARN EREPLACE_EXIST @microsoft/recognizers-text-sequence is already installed for @microsoft/recognizers-text-suite. Replacing with symlink...
lerna WARN EREPLACE_EXIST @microsoft/recognizers-text-choice is already installed for @microsoft/recognizers-text-suite. Replacing with symlink...
lerna info lifecycle postinstall
lerna info lifecycle prepublish
lerna info lifecycle prepare
lerna success Bootstrapped 8 packages
// Running tests - npm run test

> recognizers@1.1.4 test /data/personal/Recognizers-Text/JavaScript
> ava



  7897 tests passed
  2536 tests skipped
```

**Comment by tellarin** [comment]
Merging it.

**Pull request merged**
