### PR TITLE
Italian number with units (currency/temperature/age) .NET

### PR DESCRIPTION
**Pull request by LionbridgeCS**
2 test cases skipped for Age, 2 test cases skipped for currency (To be revisited after #1604 is approved)
all pass for temperature.

### CODE REVIEW

**Comment by LionbridgeCS** [comment]
skipped cases will be reviewed once the Italian Number PR is approved.

**Comment by LionbridgeCS** [comment]
The build fails checking the log the test cases failing seem to be related to German.
[00:19:30] Failed   DimensionModel (Data Row 14)
[00:19:30] Error Message:
[00:19:30]  Test method Microsoft.Recognizers.Text.NumberWithUnit.Tests.TestNumberWithUnit_German.DimensionModel

**Comment by tellarin** [comment]
@LionbridgeCS Can you update this PR and #1618 now that Numbers is merged?

**Comment by tellarin** [comment]
If you see these JavaScript build failures in setting up dependencies, please re-trigger the build once to check if it passes. 
We'll review if the current build passes.
Thanks.

**Pull request merged**
