### PR TITLE
[Python] TimexHelpers duration resolution bugfix

### LINKED ISSUE #2558: [TimexExpression] Python code not resolving timex year durations
**Describe the bug**
When only year durations are provided (eg. "next 10 years"), Python timex resolves to `start=<current datetime>` and `end=""`

**To Reproduce**
```
from datatypes_timex_expression import TimexResolver
from datetime import datetime

resolution = TimexResolver.resolve(['(2011-04-15,2021-04-15,P10Y)'], datetime.now()).values[0]
print(resolution.start, resolution.end)
```

**Platform (please complete the following information):**
 - Platform: Python
 - Environment: console app
 - Version of package: `datatypes-timex-expression==1.0.2a2`

### PR DESCRIPTION
**Pull request by omid-jf**
Fixes #2558

### CODE REVIEW

**Comment by tellarin** [comment]
Hi @omid-jf, thanks for the PR. Could you add some unit tests to show the fix is effective and we can make sure future changes won't cause any regression?

**Comment by omid-jf** [comment]
@tellarin I added the unit tests. However, I don't know why some PR checks are failing.

**Comment by tellarin** [comment]
> @tellarin I added the unit tests. However, I don't know why some PR checks are failing.

It's saying the PR is non-mergeable for some reason.

**Comment by tellarin** [comment]
@omid-jf, re-triggering the build seems to have worked. Let's see.

**Comment by omid-jf** [comment]
Thanks @tellarin 
It worked!

**Review by tellarin — APPROVED** [review]

**Pull request merged**
