### PR TITLE
[FR DateTimeV2] Add new French specs for DatePeriodExtractor/Parser

### PR DESCRIPTION
**Pull request by wumingxuanceline**
Add 352 French specs for DatePeriodExtractor,
remove duplicates :
ce week-end = this weekend, this weekend

Add 244 French specs for DatePeriodParser

### CODE REVIEW

**Review by tellarin — APPROVED** [review]

**Comment by tellarin** [comment]
I've had to clean your branch to only have the new changes. Please always create new PRs from a clean branch on top of the latest version of the Recognizers project, ok?
This PR previously included changes in 8 other unrelated files.

**Comment by tellarin** [comment]
@wumingxuanceline, you should not have added a new file to this PR. It was already approved and waiting the build to pass.
Please create separate PRs for extractor/parser pairs.

**Review by tellarin — APPROVED** [review]

**Comment by wumingxuanceline** [comment]
> @wumingxuanceline, you should not have added a new file to this PR. It was already approved and waiting the build to pass.
> Please create separate PRs for extractor/parser pairs.

I don't know why it appeared here. In fact, I've created this file with its own PR.
image

**Comment by tellarin** [comment]
> > @wumingxuanceline, you should not have added a new file to this PR. It was already approved and waiting the build to pass.
> > Please create separate PRs for extractor/parser pairs.
> 
> I don't know why it appeared here. In fact, I've created this file with its own PR.
> image

Because you added the file in the /master branch, which was the branch used for this PR.
Please create new branches for each PRs and only submit the changes from that PR. You can always create branches from the latest version of the upstream Recognizers project.

**Pull request merged**
