### PR TITLE
Add German Ordinal.relative spec examples (#1555)

### PR DESCRIPTION
**Pull request by Ablesius**
I'm not sure this is all there needs to be done; please inform me if I have to add more than this :)

### CODE REVIEW

**Comment by Ablesius** [comment]
I can't authorise at CI of Microsoft.Recognizers-BotSys, so no idea why that crashes. The error code in appveyor I don't understand - it's about an OrdinalModel-German.csv, which doesn't seem to be part of the project. Is it auto-generated from the OrdinalModel.json?

**Comment by tellarin** [comment]
BTW, the AppVeyor build should be the primary one to check in case of failures. The other one only builds .NET and run some additional internal checks that are not yet open.

**Comment by Ablesius** [comment]
Thanks for your comments! I was off for a few days, but I'm continuing on this today.

**Comment by Ablesius** [comment]
I tried to make the adaptations in accordance to PR #1550, but I'm not sure whether _all_ ordinal tests from OrdinalModel.json need to be moved to the other test (OrdinalModelEnablePreview.json, exactly as in the referenced PR), or only the ones I added. @tellarin if you could take another look, it would be awesome :)

**Comment by tellarin** [comment]
@Ablesius your change looks good. However, the linter is complaining of mixed use of whitespace and tabs in one of the C# classes. Can you convert all to whitespaces and follow the indentation style of the rest of the file?

**Pull request merged**
