### PR TITLE
[Java] Add DataType Timex Resolver Library

### PR DESCRIPTION
**Pull request by Batta32**
## Description
The DataType Timex Resolver library is missing in Java. This PR contains the migrated library from C# to Java (only code).

## Specific Changes
- Add main structure of the `recognizers-text-datatypes-timex-expression`
- Add library as submodule of `recognizers-text`
- Migrate English folder
- Migrate root files

## Testing
We created PR #2459 which contains the unit tests passing correctly (260/260) following the C# unit tests.

_Migrated structure of Timex_
image

### CODE REVIEW

**Review by tellarin — CHANGES_REQUESTED** [review]
Thanks! Looks good!
But I'll hold on merging momentarily as some library fixes are coming in #2455 and 2457 that ideally should be included here too, ok?

**Comment by Batta32** [comment]
Sure @tellarin! As soon as #2455 and #2457 are merged, we will include those changes in Java 😊.

**Comment by tellarin** [comment]
> Sure @tellarin! As soon as #2455 and #2457 are merged, we will include those changes in Java 😊.

PRs approved and merged. Feel free to make further improvements too. 😉

**Comment by Batta32** [comment]
Thanks @tellarin, we will be applying the changes of PR #2455 and #2457. We will let you know when we update this PR 😊.

**Comment by Batta32** [comment]
Hi @tellarin, we implemented the changes of PR #2455 and #2457. We updated this PR and the #2459 in order to have them reviewed and merged!

**Review by tellarin — APPROVED** [review]

**Pull request merged**
