### PR TITLE
[EN Unit Dimension] Added resolution of sub-types of dimension unit (#2097)

### PR DESCRIPTION
**Pull request by LionbridgeCSII**
Added "subtype" attribute to Resolution field for Dimension units (#2097) in .NET.

### CODE REVIEW

**Review by tellarin — APPROVED** [review]
Looks OK. The only issue to propagate to all languages is adding sub-types in their specs?

**Comment by tellarin** [comment]
Re-building PR.

**Comment by LionbridgeCSII** [comment]
> Looks OK. The only issue to propagate to all languages is adding sub-types in their specs?

yes exactly, should I add them to the other languages?

**Comment by tellarin** [comment]
> > Looks OK. The only issue to propagate to all languages is adding sub-types in their specs?
> 
> yes exactly, should I add them to the other languages?

Please do, but in another PR once this one merges. Thanks!

**Pull request merged**
