### PR TITLE
[IT NumberWithUnits] Fix for currency prefix dollari for Italian

### PR DESCRIPTION
**Pull request by KanchanKumar12**
Fix for Italian currency prefix "dollari" e.g. dollari 998

### CODE REVIEW

**Comment by KanchanKumar12** [comment]
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> 
>     
>   
> 
> >

@microsoft-github-policy-service agree [company="Genesys"]

**Comment by KanchanKumar12** [comment]
> 

@microsoft-github-policy-service agree company="Genesys"

**Comment by KanchanKumar12** [comment]
Hi @tellarin , would it be possible for this to be reviewed please?

**Comment by tellarin** [comment]
@KanchanKumar12 Sorry for the delay. I'm on vacation right now and we'll review it soon. Thanks for your contribution!

**Review by tellarin — APPROVED** [review]

**Pull request merged**
