### PR TITLE
Fix small datetime regression

### PR DESCRIPTION
**Pull request by tellarin**
And yet more consistency in spaces and linebreaks in auto-gen resources...

### CODE REVIEW

**Comment by iMicknl** [comment]
@tellarin what about adding an [.editorconfig](https://editorconfig.org/) to help maintain consistency?

**Comment by tellarin** [comment]
The problem was the auto-generated files from YAML. The original code gen was mixing tabs and whitespaces, as well as LF and CRLF; and the repo contained code with different combinations of these.
At least now most should be auto-generated code should be self-consistent. :)
This was making people frequent make mistakes in PRs and messing reviews. The pending items now is codegen for .NET. I can't find a way to have the TT transforms generate only LF. I'll probably add a post-processing script in the build at some point.

PS: Sorry, I had wrongly edited your comment. :-(

**Comment by tellarin** [comment]
Adding an .editorconfig would still be very useful though. Do you want to add it, @iMicknl? ;-)

**Comment by iMicknl** [comment]
@tellarin oops, didn't see all consistency changes were in autogenerated files. :-)

**Pull request merged**
