### PR TITLE
[DotNet][Samples] Update BotBuilderRecognizerBot sample to BotBuilder v4

### PR DESCRIPTION
**Pull request by ceciliaavila**
### Description
This is a sample that uses **BotBuilder v4** and **Recognizers** in order to update _BotBuilderRecognizerBot_ sample. 
This sample demonstrates how the Recognizers can be used to parse user input. The bot provides a basic experience for ordering roses, it starts by asking the amount of roses and then asks for a delivery date.

This PR is related to ISSUE #1473

### Changes Made
- Update BotBuilderRecognizerBot sample to BotBuilder v4.

### CODE REVIEW

**Comment by ceciliaavila** [comment]
@cleemullins, @johnataylor, what do you think of this sample?

**Comment by tellarin** [comment]
One of the reasons for the original sample was to try to make sure changes on the recognizers side wouldn't break usage in BotFramework. Would it make sense to have a sample here for a prompt, that's used by BF? Probably quite redundant with the real BF code, but may help catch breaking API changes.

**Comment by ceciliaavila** [comment]
Hi @tellarin, 
Perfect, we will leave the sample in this repository to help catch breaking API changes. 
Thanks!

> @ceciliaavila One of the reasons for the original sample was to try to make sure changes on the recognizers side wouldn't break usage in BotFramework. Would it make sense to have a sample here for a prompt, that's used by BF? Probably quite redundant with the real BF code, but may help catch breaking API changes.

**Comment by tellarin** [comment]
@ceciliaavila I took a quick look at the code, but it's not clear to me how this will catch breaking changes.
Shouldn't this sample define it's own prompt using the recognizers code directly?

**Comment by ceciliaavila** [comment]
> @ceciliaavila I took a quick look at the code, but it's not clear to me how this will catch breaking changes.
> Shouldn't this sample define it's own prompt using the recognizers code directly?

Hi @tellarin,
You are correct, in order for this sample to detect any breaking changes it should use Recognizers directly. 
We updated the code to use Recognizers for validating user's input as you can see [here](https://github.com/Microsoft/Recognizers-Text/pull/1491/files?file-filters%5B%5D=.asax&file-filters%5B%5D=.config&file-filters%5B%5D=.cs&file-filters%5B%5D=.htm&file-filters%5B%5D=.json&file-filters%5B%5D=.md#diff-03b5edc86e7deca13c141348f3977719R180).

Please, let us know if there is anything else we need to improve.
 
Thanks!

**Pull request merged**
