### PR TITLE
[DE Unit] Update Temperature entries

### PR DESCRIPTION
**Pull request by dNsl9r**
Added entries for kelvin, celsius for better results in LUIS

### CODE REVIEW

**Comment by dNsl9r** [comment]
Hi @tellarin - I'm not very familiar with the build process, I will take at look into it when I've got time and will process the requested changes. Thank you!

**Comment by tellarin** [comment]
@dNsl9r adding the test spec cases is the most important, as they should be proper German full sentences. 
We can help with the auto-gen resource files. Thanks!

**Comment by tellarin** [comment]
@dNsl9r, thanks for the specs. I've fixed the json syntax and added the latest auto-gen resource files.
It should be OK to merge as soon as the build finishes.

**Comment by dNsl9r** [comment]
thank you!

**Pull request merged**
