### PR TITLE
Change target framework to netstandard2.0

### PR DESCRIPTION
**Pull request by amitstein**
Changed Target framework to netstandard 2.0. It was necessary to downgrade System.Collections.Immutable package to version 1.3.1 to work with .Net Framework 4.6.2 projects ([related issue](https://github.com/dotnet/standard/issues/534#issuecomment-358712093)).

### CODE REVIEW

**Comment by cleemullins** [comment]
Any chance you could do that today? :)

________________________________

**Comment by tellarin** [comment]
Soon, @cleemullins :)

**Comment by amitstein** [comment]
Hi @tellarin,
We converted the projects to multi-target.

**Comment by amitstein** [comment]
Hi @tellarin 
When target framework 4.6.2 is replaced with Net Standard 2.0 there is a conflict when an app using Net Framework 4.6.2 tries to locate System.Collections.Immutable.
The branch that you mentioned works, so i will close this PR.

thanks!

**Pull request closed without merging**
