### PR TITLE
[FR DateTimeV2] Add new French specs for DateExtractor/Parser

### PR DESCRIPTION
**Pull request by wumingxuanceline**
Add 139 French specs for DateExtractor, 
remove duplicates : 
je vais rentrer le 22 avril	= i'll go back april 22,	i'll go back on 4.22,	 i'll go back 4/22
je vais rentrer le 22/04	= i'll go back at 4.22,	i'll go back 22/04
je vais rentrer vendredi	= i'll go back on friday,	i'll go back friday

Add 121 French specs for DateParser, 
remove duplicates : 
Je vais rentrer le 22 avril	= I'll go back on 4.22,	I'll go back at 4.22,	 I'll go back 22/04
Je vais rentrer le 22/04	= I'll go back in 4.22,	I'll go back on 4/22,	 I'll go back 4/22
Je vais rentrer vendredi	= I'll go back on Friday,	I'll go back Friday
Nous avons eu une réunion il y a un mois et 21 jours	=  We had a meeting 1 month 21 days ago,  We had a meeting 1 month and 21 days ago

### CODE REVIEW

**Comment by ChopperMan33** [comment]
Hi, @wumingxuanceline 
There's some index mismatch in this two files. You can see them in: 
[issue2430.txt](https://github.com/microsoft/Recognizers-Text/files/5779258/issue2430.txt)

**Comment by wumingxuanceline** [comment]
> Hi, @wumingxuanceline
> There's some index mismatch in this two files. You can see them in:
> [issue2430.txt](https://github.com/microsoft/Recognizers-Text/files/5779258/issue2430.txt)

Reply : 
[for mismatches.docx](https://github.com/microsoft/Recognizers-Text/files/5779825/for.mismatches.docx)

**Comment by tellarin** [comment]
Hi folks,
let's try to keep discussion in comments as much as possible. Attached files make it much harder to follow and to track issues.

**Comment by tellarin** [comment]
@wumingxuanceline, if the indices are not updated to match the new French sentences, than the specs are invalid.
Start and end indices specify where in the input sentence the extracted text for each entity is located.
Small mistakes (index being wrong by 1 or 2 can be automatically fixed, but not if no index was updated for French (just repeated that indices for English, which don't apply anymore). @XiaoxiaoMa0815 FYI.

**Review by tellarin — CHANGES_REQUESTED** [review]
It seems many specs didn't have any start/end index updated in the French localization. Please review.

**Comment by wumingxuanceline** [comment]
> @wumingxuanceline, if the indices are not updated to match the new French sentences, than the specs are invalid.
> Start and end indices specify where in the input sentence the extracted text for each entity is located.
> Small mistakes (index being wrong by 1 or 2) can be automatically fixed, but indices should not be just repeated from English (which are no longer applicable).
> @XiaoxiaoMa0815 FYI.
> We can have someone write a script to automatically calculate these in future PRs, but there may still be cases that need manual fix.

Thanks. Could you please give us a brief explanation about the indices update? cause we are not expert in this. Please feel free to keep us updated.

**Comment by tellarin** [comment]
@wumingxuanceline, @XiaoxiaoMa0815, I've pushed some automatic fixes for the start/end/length issues here. You can see the changes in the last commit in this PR. As soon as the build passes, we can merge this.

We've now added a version of the ValidationTool in /Tools/bin/ValidationTool.exe. you can run this tool on your new specs to check for errors. And if you specifify the '-s' parameter, it will also try to automatically calculate indices, so they don't need to be updated manually.

Please move ahead with the PRs for the other specs and use this tool to validate before pushing.

Also, when creating a PR, it's better to not create it from the /master branch. Each PR should ideally come from its own branch.

Thanks!

@ChopperMan33 FYI.

**Review by tellarin — APPROVED** [review]

**Comment by tellarin** [comment]
We noticed an error in the build that didn't break it, but we're holding the merge until it's fixed on our side.
Please continue with the next PRs.

**Pull request merged**
