### PR TITLE
[ZH DateTimeV2] Fixes for holiday extraction issues #2350 & #2348

### PR DESCRIPTION
**Pull request by Tao2301230**
[Python | ZH DateTimeV2] Relative holidays like ＂今年圣诞节＂ not properly recognized #2350
[Python | ZH DateTimeV2] holiday words cannot be recognized #2348

### CODE REVIEW

**Review by tellarin — CHANGES_REQUESTED** [review]
It seems the three new tests still fail in Python. Could you take a look at the build result?

**Comment by Tao2301230** [comment]
Ok, sorry for the trouble.

**Comment by tellarin** [comment]
> Ok, sorry for the trouble.

No worries. Build failures are common. Especially when it's a first PR in a new project.

**Comment by Tao2301230** [comment]
Hi @tellarin , 
Sorry, I still cannot make it. From what I found, the Recognizers package doesn't repack with my code after I run build.sh.
Are there any processes I missed besides updating the code in libraries directory?

**Comment by ChopperMan33** [comment]
Hi,  @Tao2301230 
For Python, you only need to run 'run.sh' script to repack the code. And you should put your new unit test cases into `HolidayExtractor.json` and `HolidayParser.json` rather than `DateExtractor.json` and `DateParser.json`.
I am now helping @tellarin with this project. If you have any problem, please feel free to contact me.

**Review by Tao2301230 — COMMENTED** [review]
update specs/holiday*.json

**Comment by Tao2301230** [comment]
hi @ChopperMan33,
Thank you so much! This time it works.

**Review by tellarin — APPROVED** [review]

**Comment by tellarin** [comment]
@Tao2301230, congratulations on your first two fixes! 👍 
Thanks for the contributions.

**Comment by ChopperMan33** [comment]
@Tao2301230 You are welcomed. And congratulations!

**Pull request merged**
