### PR TITLE
[FR DateTimeV2] Add new French specs for DateExtractor/Parser

### PR DESCRIPTION
**Pull request by wumingxuanceline**
143 new specs for DateExtractor
127 new specs for DateParser

### CODE REVIEW

**Comment by wumingxuanceline** [comment]
Hi Börje, we added news specs for these two files and had already checked them for many times, but one of them still failed because of "empty or duplicate inputs in Specs". Could you please have a check and point out the problem ? Thanks.

**Comment by ChopperMan33** [comment]
Hi @wumingxuanceline ,
I find you add an extra characters `[`  in row 1451 https://github.com/microsoft/Recognizers-Text/commit/04a311aecd1daedda38ed68eb32ea9b721018570#diff-d3279030e99103578e94608f49dd2edabfa1343fb0323424d7ffbada14b79680R1451, which will make the json file duplicate.

**Comment by wumingxuanceline** [comment]
> Hi @wumingxuanceline ,
> I find you add an extra character `[` in row 1451 [04a311a#diff-d3279030e99103578e94608f49dd2edabfa1343fb0323424d7ffbada14b79680R1451](https://github.com/microsoft/Recognizers-Text/commit/04a311aecd1daedda38ed68eb32ea9b721018570#diff-d3279030e99103578e94608f49dd2edabfa1343fb0323424d7ffbada14b79680R1451), which will make the json file duplicate.

**Comment by ChopperMan33** [comment]
Hi @wumingxuanceline ,
You've already fixed the brackets problem. But there are 18 duplicate test cases like "je vais rentrer vendredi", 
"je vais rentrer le 22/04" and so on.
They caused the error. You can find them in https://ci.appveyor.com/project/tellarin/recognizers-text/builds/37054975.

**Comment by wumingxuanceline** [comment]
Hi @ChopperMan33 ,
Thanks for your help. But these cases are not actually duplicate. In fact, they are different inputs but have the same french version, though we've tried to vary the expressions. Therefore, the rest files will also have the same problem. Is there any solution for the work ?

**Review by tellarin — CHANGES_REQUESTED** [review]
Build is failing due to duplicate spec cases.

**Comment by tellarin** [comment]
@wumingxuanceline, this means that they are now duplicate in French. 
There's no need to have more than one case with the exact same input sentence and reference parameters. If there's no other applicable variation for these cases (preserving the original case meaning in English) please remove the duplicates.
When removing duplicates, please update the PR description to mention what the original cases were in English and to which case they map in French.

Something like:
"I'll go back on Friday", and "I'll go back Friday" map to “je vais rentrer vendredi” in French.

**Comment by wumingxuanceline** [comment]
> @wumingxuanceline, this means that they are now duplicate in French.
> There's no need to have more than one case with the exact same input sentence and reference parameters. If there's no other applicable variation for these cases (preserving the original case meaning in English) please remove the duplicates.
> When removing duplicates, please update the PR description to mention what the original cases were in English and to which case they map in French.
> 
> Something like:
> "I'll go back on Friday", and "I'll go back Friday" map to “je vais rentrer vendredi” in French.

**Comment by wumingxuanceline** [comment]
Will start a new PR

**Pull request closed without merging**
