### PR TITLE
[DotNet][Datetime] Remove unused regexes from Dutch, French, Portuguese, Japanese, and Italian extractors.

### PR DESCRIPTION
**Pull request by GasparAcevedoZainSouthworks**
# Description
Remove unused regexes from Dutch, French, Portuguese, Japanese, and Italian extractors. This is just to clean the code.

### CODE REVIEW

**Comment by iMicknl** [comment]
@GasparAcevedoZainSouthworks Duch DateTime is a work in progress currently. On what criteria is the decision based to remove some regexes? On untranslated regexes or something else?
I would prefer not to remove the unused Dutch regexes, since it is a work in progress. (if based on untranslated regexes)

**Comment by tellarin** [comment]
@GasparAcevedoZainSouthworks can we do the same @ParadoxARG did on #1408?
This should address @iMicknl's concerns too.

**Comment by ParadoxARG** [comment]
@tellarin @iMicknl We applied the same criteria that were discussed on PR #1408. We only removed the same regexes that were removed from English because they were not being used. 
Anyways we decided to split the PR and we are going to put Dutch in another one. This way we can keep the changes on-hold until the development is completed.

**Comment by ParadoxARG** [comment]
Changes applied. Dutch was removed from the PR.

**Comment by tellarin** [comment]
I'll temporarily close the 4 PRs (#1407, #1408, #1421, #1426) related to removing regexes as there was no time to properly review and many folks here will be on a week-long holiday this week. I'll re-open when everyone is back.
Sorry for the delay.

**Pull request closed without merging**
