### PR TITLE
[ZH Number] Fixed when the number string is long the extraction take a long time (#2747)

### PR DESCRIPTION
**Pull request by aitelint**
Fix to issue #2747.

The slowdown was caused by complex lookarounds used to avoid extracting numbers from percentage expressions in certain patterns. But since in English this kind of filtering is not implemented, they do not seem to be necessary and have been removed.

Test cases added to Chinese NumberModel and CurrencyModel.

Another issue observed is that long numbers in Chinese characters do not seem to be resolved correctly.

### CODE REVIEW

**Comment by tellarin** [comment]
Hmmm. This is a bit tricky. In other languages a number is returned too if "inside" a percentage, like "17" in "17%". But here the whole number and percentage are recognized together.
Regarding the long number resolution issue, any insights on what is the type of failure?

**Review by tellarin — CHANGES_REQUESTED** [review]
Marking as not to merge directly. We need to consider if there's a side effect first.

**Review by tellarin — APPROVED** [review]
Actually, upon a closer check these seem OK. Not sure why the previous extra processing was there.

**Comment by tellarin** [comment]
@aitelint Regarding the long number resolution issue, any insights on what is the type of failure?
Should we open an issue for it?

**Comment by aitelint** [comment]
> @aitelint Regarding the long number resolution issue, any insights on what is the type of failure? Should we open an issue for it?

I have not investigated the problem for now, only observed that the resolution is not correct, e.g.
"四千五百六十九万八千三百一十一亿四千八百七十二万五千三百八十二" -> 831194415382 instead of 4569831148725382
"二千零二十一万零七百二十一亿一千三百二十一万三千六百三十五" -> 72133423635 instead of 2021072113213635

Yes, the problem could be addressed in a separate issue (not sure however if these long expressions are used in practice)

**Pull request merged**
