### PR TITLE
[.NET] Enable C# 9 and minor .NET code cleanup

### PR DESCRIPTION
**Pull request by iamcarbon**
- Enables C#9
- Replaces a few culture specific comparisons against constant string with is pattern
- Removes a few unused using statements

### CODE REVIEW

**Comment by iamcarbon** [comment]
Ready for review.

**Comment by tellarin** [comment]
@iamcarbon This looks mostly OK. Can you give me permission to push to your PR branch, so I can make some small changes to merge?

**Comment by tellarin** [comment]
Closing this PR as its superseeded by #2679.

**Review by tellarin — COMMENTED** [review]
All projects should have C# 9 enabled.

**Pull request closed without merging**
