### PR TITLE
[DE DateTimeV2] Fixed set and time being incorrectly mixed during recognition (#2334)

### PR DESCRIPTION
**Pull request by LionbridgeCSII**
Fix to issue #2334. 

The behaviour of the extractor has been conformed to the English one. 
But, should we modify it to extract "jeden Tag um 19:13 Uhr" as a single entity? This happens already when the time entity is at the end of the utterance (e.g. "Ich gehe jeden Tag um 3 Uhr Nachmittags").

### CODE REVIEW

**Comment by tellarin** [comment]
> The behaviour of the extractor has been conformed to the English one.
> But, should we modify it to extract "jeden Tag um 19:13 Uhr" as a single entity? This happens already when the time entity is at the end of the utterance (e.g. "Ich gehe jeden Tag um 3 Uhr Nachmittags").

Ideally yes, I think. But what's the behaviour in English for the sentences corresponding to these two exact cases? Always separate?

**Review by tellarin — APPROVED** [review]

**Comment by LionbridgeCSII** [comment]
> Ideally yes, I think. But what's the behaviour in English for the sentences corresponding to these two exact cases? Always separate?

Yes, in English they are always separate because the regex that should check for "every day" before the time entity (BeforeEachDayRegex) is set to null. So at the moment, only cases where "every day" follows the time are extracted as a single Set entity (e.g. "7:13 p.m. every day").

**Comment by tellarin** [comment]
Let's leave as-is in this PR for now then. Can you resolve the conflicts to merge? Thanks!

**Comment by LionbridgeCSII** [comment]
> Let's leave as-is in this PR for now then. Can you resolve the conflicts to merge? Thanks!

ok, conflict solved.

**Pull request merged**
