### PR TITLE
[SV Unit] Add support for Unit - Age, Temperature and Dimension

### PR DESCRIPTION
**Pull request by pete1854**
Adding support for Unit - Age and Temperature. All related patterns and specs translated. All tests pass.

### CODE REVIEW

**Comment by pete1854** [comment]
Changing status to draft. Patterns and specs for Unit - Dimension are almost done and I would like to include that as well in this PR.

**Comment by pete1854** [comment]
@tellarin - What is the best way to add recognition of the swedish unit "Mil"? Should it be added to the LengthSuffixList as a completely new entry, or is there any other ways to extend the capability of the recognizer?

**Comment by pete1854** [comment]
Support for "mil" can be added at a later date. Not a priority at this stage.

**Comment by tellarin** [comment]
Thanks, @pete1854! We'll try to review and merge as soon as possible.

**Review by tellarin — APPROVED** [review]

**Pull request merged**
