### PR TITLE
[EN DateTimeV2] Fixed incorrect parsing of period mentions like 'last two quarters' (#2656)

### PR DESCRIPTION
**Pull request by aitelint**
Fix to issue #2656 in .NET and JavaScript.

Did not tackle the pattern in Number because it does not seem wrong to extract "two quarters" as fraction. 
I can find expressions that use it, e.g. "the last two quarters of the book are dedicated to it".

Test cases added to DateTimeModel.

### CODE REVIEW

**Review by tellarin — APPROVED** [review]

**Comment by tellarin** [comment]
@aitelint, Could you please resolve the conflicts to merge? Thanks.

**Comment by aitelint** [comment]
> @aitelint, Could you please resolve the conflicts to merge? Thanks.

conflicts solved

**Comment by tellarin** [comment]
@aitelint Sorry, this one fell throught the cracks and I didn't see you had resolved the conflicts. Can you resolve again to merge?

**Comment by aitelint** [comment]
> @aitelint Sorry, this one fell throught the cracks and I didn't see you had resolved the conflicts. Can you resolve again to merge?

no problem, solved.

**Pull request merged**
